import './styles.css';

const KEY = 'field-sales-visit-app-v1';
const blank = { employee: '', beat: '', rate: 12, started: false, start: null, last: null, distance: 0, valid: 0, invalid: 0, visits: [], active: null, close: null };
const state = { ...blank, ...JSON.parse(localStorage.getItem(KEY) || '{}') };
const save = () => localStorage.setItem(KEY, JSON.stringify(state));
const $ = (id) => document.getElementById(id);
const now = () => new Date();
const gps = (done, fail) => navigator.geolocation?.getCurrentPosition(p => done({ lat: p.coords.latitude, lng: p.coords.longitude }), () => fail('GPS permission is required.')) || fail('GPS is not supported by this browser.');
const distance = (a, b) => { if (!a || !b) return 0; const r = 6371, dLat = (b.lat-a.lat)*Math.PI/180, dLng = (b.lng-a.lng)*Math.PI/180; const x = Math.sin(dLat/2)**2 + Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLng/2)**2; return r * 2 * Math.atan2(Math.sqrt(x), Math.sqrt(1-x)); };
const status = (id, text, type = '') => { $(id).textContent = text; $(id).className = `status ${type}`; };
const refresh = () => { $('distance').textContent = `${state.distance.toFixed(2)} km`; $('claim').textContent = `₹${(state.distance * Number(state.rate || 0)).toFixed(2)}`; $('valid').textContent = `${state.valid}/20`; $('invalid').textContent = state.invalid; $('startTime').value = state.start ? new Date(state.start).toLocaleString() : 'Not started'; $('employee').value = state.employee; $('beat').value = state.beat; $('rate').value = state.rate; $('log').innerHTML = state.visits.length ? state.visits.map(v => `<tr><td>${v.name}</td><td>${v.minutes.toFixed(1)} min</td><td>${v.valid ? '<b class="good">Valid</b>' : '<b class="bad">Invalid</b>'}</td></tr>`).join('') : '<tr><td colspan="3">No visits yet.</td></tr>'; };
const report = () => `*Daily Closing Report*\nEmployee: ${state.employee || 'N/A'}\nBeat: ${state.beat || 'N/A'}\nValid Visits: ${state.valid}/20\nInvalid Visits: ${state.invalid}\nOutlets Checked: ${state.visits.length}\nTravel Distance: ${state.distance.toFixed(2)} km\nTravel Claim: ₹${(state.distance * Number(state.rate || 0)).toFixed(2)}\nClosing GPS: ${state.close ? `${state.close.lat.toFixed(5)}, ${state.close.lng.toFixed(5)}` : 'N/A'}`;

document.querySelector('#app').innerHTML = `<main class="app"><header><div class="logo">FS</div><div><h1>Field Sales Visit Tracker</h1><p>GPS attendance · outlet visits · daily claim</p></div></header><section class="grid"><article class="card"><h2>Daily start / self check-in</h2><div class="fields"><label>Employee<input id="employee" placeholder="Sales representative"></label><label>Assigned beat<input id="beat" placeholder="Beat name"></label><label>Travel rate / km<input id="rate" type="number" min="0" value="12"></label><label>Start time<input id="startTime" readonly value="Not started"></label></div><button id="start">Start beat and capture GPS</button><button id="reset" class="secondary">Reset day</button><div id="startStatus" class="status">Ready to start.</div><div class="metrics"><div><small>Distance</small><strong id="distance">0.00 km</strong></div><div><small>Claim</small><strong id="claim">₹0.00</strong></div><div><small>Valid visits</small><strong id="valid">0/20</strong></div><div><small>Invalid visits</small><strong id="invalid">0</strong></div></div></article><article class="card"><h2>Outlet visit</h2><label>Outlet name<input id="outlet" placeholder="Shop / outlet name"></label><label>SKU stock check<textarea id="stock" placeholder="SKU: quantity, one per line"></textarea></label><label>SKU order booking<textarea id="orders" placeholder="SKU: order quantity, one per line"></textarea></label><label>Display / competition photo<input id="photo" type="file" accept="image/*" capture="environment"></label><label>No-order reason<textarea id="reason" placeholder="Required when there is no order"></textarea></label><button id="in" class="secondary">Outlet check-in</button><button id="out">Outlet check-out</button><div id="outletStatus" class="status">No outlet visit started.</div></article><article class="card"><h2>Day closing</h2><label>Closing GPS photo<input id="closingPhoto" type="file" accept="image/*" capture="environment"></label><button id="close" class="danger">Closing check-out with GPS</button><div id="closeStatus" class="status">Day is in progress.</div><textarea id="message" readonly placeholder="WhatsApp-ready report appears here"></textarea><button id="copy" class="secondary">Copy WhatsApp message</button></article><article class="card full"><h2>Visit log</h2><table><thead><tr><th>Outlet</th><th>Duration</th><th>Result</th></tr></thead><tbody id="log"></tbody></table></article></section></main>`;

$('start').onclick = () => { state.employee = $('employee').value.trim(); state.beat = $('beat').value.trim(); state.rate = Number($('rate').value || 0); if (!state.employee || !state.beat) return status('startStatus', 'Enter employee and assigned beat first.', 'bad'); gps(p => { state.started = true; state.start = Date.now(); state.last = p; state.distance = 0; save(); refresh(); status('startStatus', `Started ${state.beat}; GPS captured.`, 'good'); }, e => status('startStatus', e, 'bad')); };
$('in').onclick = () => { if (!state.started) return status('outletStatus', 'Start the assigned beat first.', 'bad'); const name = $('outlet').value.trim(); if (!name) return status('outletStatus', 'Enter an outlet name.', 'bad'); gps(p => { state.active = { name, at: Date.now(), gps: p }; save(); status('outletStatus', `Checked in to ${name}. Stay 10–30 minutes.`, 'good'); }, e => status('outletStatus', e, 'bad')); };
$('out').onclick = () => { if (!state.active) return status('outletStatus', 'Check in to an outlet first.', 'bad'); gps(p => { const minutes = (Date.now()-state.active.at)/60000, valid = minutes >= 10 && minutes <= 30; state.distance += distance(state.last, p); state.last = p; state.visits.push({ name: state.active.name, minutes, valid }); valid ? state.valid++ : state.invalid++; state.active = null; save(); refresh(); status('outletStatus', valid ? `Valid visit recorded (${minutes.toFixed(1)} minutes).` : `Invalid visit: duration must be 10–30 minutes.`, valid ? 'good' : 'bad'); }, e => status('outletStatus', e, 'bad')); };
$('close').onclick = () => { if (!state.started) return status('closeStatus', 'Start the day first.', 'bad'); gps(p => { state.close = p; $('message').value = report(); save(); status('closeStatus', 'Closing GPS captured and report generated.', 'good'); }, e => status('closeStatus', e, 'bad')); };
$('copy').onclick = () => navigator.clipboard?.writeText($('message').value).then(() => status('closeStatus', 'WhatsApp message copied.', 'good'));
$('reset').onclick = () => { if (confirm('Reset today\'s route and visits?')) { Object.assign(state, blank, { rate: Number($('rate').value || 12) }); save(); refresh(); $('message').value = ''; status('startStatus', 'Day reset.', 'good'); } };
$('rate').oninput = () => { state.rate = Number($('rate').value || 0); save(); refresh(); };
refresh();
