import './styles.css';

const KEY = 'field-sales-visit-app-v1';
const defaults = { employee: '', beat: '', rate: 12, started: false, start: null, last: null, distance: 0, valid: 0, invalid: 0, visits: [], active: null, close: null };
let state = { ...defaults, ...load() };
const $ = (id) => document.getElementById(id);
const save = () => localStorage.setItem(KEY, JSON.stringify(state));
function load() { try { return JSON.parse(localStorage.getItem(KEY) || '{}'); } catch { return {}; } }
function gps(ok, fail) { if (!navigator.geolocation) return fail('GPS is not supported on this device.'); navigator.geolocation.getCurrentPosition(p => ok({ lat: p.coords.latitude, lng: p.coords.longitude, accuracy: p.coords.accuracy }), () => fail('Please allow GPS permission to continue.'), { enableHighAccuracy: true, timeout: 15000, maximumAge: 0 }); }
function km(a, b) { if (!a || !b) return 0; const r=6371, x=(b.lat-a.lat)*Math.PI/180, y=(b.lng-a.lng)*Math.PI/180, z=Math.sin(x/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(y/2)**2; return r*2*Math.atan2(Math.sqrt(z),Math.sqrt(1-z)); }
function status(id, text, type='') { $(id).textContent=text; $(id).className=`notice ${type}`; }
function esc(v) { return String(v || '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
function report() { return `*Daily Closing Report*\nEmployee: ${state.employee || 'N/A'}\nBeat: ${state.beat || 'N/A'}\nValid Visits: ${state.valid}/20\nInvalid Visits: ${state.invalid}\nOutlets Checked: ${state.visits.length}\nTravel Distance: ${state.distance.toFixed(2)} km\nTravel Claim: ₹${(state.distance * Number(state.rate || 0)).toFixed(2)}\nClosing GPS: ${state.close ? `${state.close.lat.toFixed(5)}, ${state.close.lng.toFixed(5)}` : 'N/A'}`; }

$('app').innerHTML = `<div class="mobile-app"><header class="appbar"><button class="menu">☰</button><div><h1>Self Report-In</h1><p>FMCG Beat Planner · ${new Date().toLocaleDateString(undefined,{day:'2-digit',month:'short'})}</p></div><div class="app-actions"><span>↻</span><span>ⓘ</span></div></header><nav class="tabs"><button class="tab active" data-view="dashboard">Dashboard</button><button class="tab" data-view="outlets">Outlets</button><button class="tab" data-view="route">Location</button><button class="tab" data-view="report">Reports</button></nav><main>
<section id="dashboard" class="view active"><div class="profile"><div class="avatar">SE</div><div><strong id="welcome">Good morning, Sales Executive</strong><small id="profileBeat">Assigned beat not started</small></div><span class="bell">♧</span></div><div class="quick-grid"><button class="quick" data-jump="startPanel"><i>⌁</i><b id="qVisits">0</b><span>Valid visits</span></button><button class="quick" data-jump="visitPanel"><i>⌖</i><b id="qOutlets">0</b><span>Today's outlets</span></button><button class="quick" data-jump="reportPanel"><i>₹</i><b id="qClaim">₹0</b><span>Travel claim</span></button></div><article class="section-card"><h2>Beat execution</h2><div class="progress-label"><span>Daily target</span><b id="progressText">0 / 20 valid visits</b></div><div class="progress"><i id="progressBar"></i></div><div class="beat-summary"><div><small>Beat</small><strong id="beatSummary">Not assigned</strong></div><div><small>Distance</small><strong id="distance">0.00 km</strong></div><div><small>Status</small><strong id="routeStatus">Not started</strong></div></div></article><article class="section-card workflow" id="startPanel"><div class="section-title"><div><small>STEP 01</small><h2>Attendance & beat start</h2></div><span class="state-badge" id="startState">PENDING</span></div><label>Employee name<input id="employee" placeholder="Enter your name"></label><label>Assigned beat name<input id="beat" placeholder="e.g. Thanjavur North"></label><div class="twocol"><label>Rate / km<input id="rate" type="number" value="12" min="0"></label><label>Start time<input id="startTime" value="Not started" readonly></label></div><button id="start" class="primary wide">✓ Start beat & capture GPS</button><button id="reset" class="link-btn">Reset today's route</button><div id="startStatus" class="notice">Ready to start your assigned beat.</div></article></section>
<section id="outlets" class="view"><div class="page-title"><div><small>FIELD EXECUTION</small><h2>Outlet visits</h2></div><span class="counter" id="count">0 visits</span></div><div class="search"><span>⌕</span><input id="outletSearch" placeholder="Search outlet or channel partner"></div><article class="section-card workflow" id="visitPanel"><div class="section-title"><div><small>STEP 02 · 10–30 MINUTES</small><h2>Check in to outlet</h2></div><span class="state-badge orange">VISIT</span></div><label>Outlet / shop name<input id="outlet" placeholder="Enter outlet name"></label><div class="twocol"><label>Stock check<textarea id="stock" placeholder="SKU : quantity"></textarea></label><label>Order booking<textarea id="orders" placeholder="SKU : quantity"></textarea></label></div><label class="upload">▣ Display & competition photo<input id="photo" type="file" accept="image/*" capture="environment"></label><label>No-order reason<input id="reason" placeholder="Required when no order"></label><div class="twocol buttons"><button id="in" class="secondary">✓ Check in</button><button id="out" class="primary">Check out →</button></div><div id="outletStatus" class="notice">No outlet visit in progress.</div></article><article class="section-card"><div class="section-title"><h2>Today's visit log</h2><span class="counter" id="logCount">0</span></div><div id="log" class="visit-list"><div class="empty">No outlet visits recorded yet.</div></div></article></section>
<section id="route" class="view"><div class="page-title"><div><small>GPS TRACKING</small><h2>Live location</h2></div><span class="gps-chip">● GPS ready</span></div><article class="map-card"><div class="map-grid"></div><div class="map-label">📍 Current route</div><div class="map-road road-one"></div><div class="map-road road-two"></div><div class="map-pin pin-a">●</div><div class="map-pin pin-b">●</div><div class="map-pin pin-c">●</div><div class="map-controls"><button>+</button><button>−</button></div></article><article class="section-card location-detail"><div><small>START LOCATION</small><strong id="startGps">Not captured</strong></div><div><small>TRAVELLED</small><strong id="routeDistance">0.00 km</strong></div><div><small>RATE</small><strong id="routeRate">₹12/km</strong></div></article></section>
<section id="report" class="view"><div class="page-title"><div><small>DAY CLOSING</small><h2>Reports & claims</h2></div></div><article class="section-card workflow" id="reportPanel"><div class="section-title"><div><small>STEP 03</small><h2>Close & submit</h2></div><span class="state-badge">END OF DAY</span></div><p class="muted">Capture your final GPS location and generate a WhatsApp-ready daily report.</p><label class="upload">▣ Closing GPS photo<input id="closingPhoto" type="file" accept="image/*" capture="environment"></label><button id="close" class="danger wide">Closing check-out with GPS</button><div id="closeStatus" class="notice">Day is still in progress.</div><textarea id="message" class="report" readonly placeholder="Your closing report will appear here"></textarea><button id="copy" class="secondary wide">▣ Copy WhatsApp report</button></article><article class="section-card claim-card"><span class="claim-icon">₹</span><div><small>ESTIMATED TRAVEL CLAIM</small><strong id="claim">₹0.00</strong><p>Calculated from GPS distance</p></div></article></section>
</main><nav class="bottom-nav"><button class="active" data-view="dashboard">⌂<span>Home</span></button><button data-view="outlets">▤<span>Outlets</span></button><button data-view="route">⌖<span>Location</span></button><button data-view="report">▥<span>Reports</span></button></nav></div>`;

function refresh() { $('employee').value=state.employee; $('beat').value=state.beat; $('rate').value=state.rate; $('welcome').textContent=`Good morning, ${state.employee || 'Sales Executive'}`; $('profileBeat').textContent=state.beat ? `Assigned beat · ${state.beat}` : 'Assigned beat not started'; $('beatSummary').textContent=state.beat || 'Not assigned'; $('distance').textContent=`${state.distance.toFixed(2)} km`; $('routeDistance').textContent=`${state.distance.toFixed(2)} km`; $('routeRate').textContent=`₹${state.rate}/km`; $('claim').textContent=`₹${(state.distance*Number(state.rate||0)).toFixed(2)}`; $('qClaim').textContent=`₹${(state.distance*Number(state.rate||0)).toFixed(0)}`; $('valid').textContent=`${state.valid} / 20`; $('qVisits').textContent=state.valid; $('qOutlets').textContent=state.visits.length; $('progressText').textContent=`${state.valid} / 20 valid visits`; $('progressBar').style.width=`${Math.min(state.valid/20*100,100)}%`; $('routeStatus').textContent=state.started?'In progress':'Not started'; $('startState').textContent=state.started?'ACTIVE':'PENDING'; $('startTime').value=state.start?new Date(state.start).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'Not started'; $('count').textContent=`${state.visits.length} visit${state.visits.length===1?'':'s'}`; $('logCount').textContent=state.visits.length; $('startGps').textContent=state.start?`${state.last?.lat.toFixed(5)}, ${state.last?.lng.toFixed(5)}`:'Not captured'; $('log').innerHTML=state.visits.length?state.visits.map(v=>`<div class="visit-row"><div class="visit-icon">⌖</div><div><strong>${esc(v.name)}</strong><small>${new Date(v.at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})} · ${v.minutes.toFixed(1)} minutes</small></div><span class="${v.valid?'valid':'invalid'}">${v.valid?'✓ Valid':'× Invalid'}</span></div>`).join(''):'<div class="empty">No outlet visits recorded yet.</div>'; }
function selectView(view) { document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===view)); document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===view)); window.scrollTo({top:0,behavior:'smooth'}); }
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>selectView(b.dataset.view)); document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{selectView('dashboard'); setTimeout(()=>$(b.dataset.jump)?.scrollIntoView({behavior:'smooth'}),50);});
$('start').onclick=()=>{ state.employee=$('employee').value.trim(); state.beat=$('beat').value.trim(); state.rate=Number($('rate').value||0); if(!state.employee||!state.beat)return status('startStatus','Enter employee name and assigned beat first.','bad'); gps(p=>{state.started=true;state.start=Date.now();state.last=p;state.distance=0;save();refresh();status('startStatus',`Beat started. GPS accuracy ±${Math.round(p.accuracy||0)}m.`,'good');},e=>status('startStatus',e,'bad')); };
$('in').onclick=()=>{if(!state.started)return status('outletStatus','Start the assigned beat first.','bad');const name=$('outlet').value.trim();if(!name)return status('outletStatus','Enter an outlet name.','bad');if(state.active)return status('outletStatus','Check out from the current outlet first.','bad');gps(p=>{state.active={name,at:Date.now(),gps:p};save();status('outletStatus',`Checked in to ${name}. Visit window: 10–30 minutes.`,'good');},e=>status('outletStatus',e,'bad'));};
$('out').onclick=()=>{if(!state.active)return status('outletStatus','Check in to an outlet first.','bad');gps(p=>{const minutes=(Date.now()-state.active.at)/60000,valid=minutes>=10&&minutes<=30;state.distance+=km(state.last,p);state.last=p;state.visits.push({name:state.active.name,at:state.active.at,minutes,valid});valid?state.valid++:state.invalid++;state.active=null;save();refresh();status('outletStatus',valid?`Valid visit recorded (${minutes.toFixed(1)} minutes).`:'Invalid visit: duration must be between 10 and 30 minutes.',valid?'good':'bad');},e=>status('outletStatus',e,'bad'));};
$('close').onclick=()=>{if(!state.started)return status('closeStatus','Start the day first.','bad');gps(p=>{state.close=p;$('message').value=report();save();status('closeStatus','Closing GPS captured. Report is ready to share.','good');},e=>status('closeStatus',e,'bad'));}; $('copy').onclick=()=>{if(!$('message').value)return status('closeStatus','Generate the report first.','bad');navigator.clipboard?.writeText($('message').value).then(()=>status('closeStatus','WhatsApp report copied.','good'));}; $('reset').onclick=()=>{if(confirm("Reset today's route and visits?")){state={...defaults,rate:Number($('rate').value||12)};save();refresh();$('message').value='';status('startStatus','Day reset. Ready to start again.','good');}}; $('rate').oninput=()=>{state.rate=Number($('rate').value||0);save();refresh();}; refresh();
